# Generated by Django 4.1.6 on 2023-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_deposits_terminate_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
