# Generated by Django 4.1.6 on 2023-05-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sum', models.FloatField()),
                ('currency', models.CharField(blank='Enter your choice', choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('PLN', 'PLN'), ('CHF', 'CHF'), ('GBP', 'GBP')], max_length=30)),
                ('rate', models.FloatField()),
                ('period', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_gv', models.CharField(max_length=5)),
                ('coupons', models.IntegerField()),
                ('total_payment', models.FloatField()),
                ('coupons_payment', models.FloatField()),
                ('return_sum_gv', models.FloatField()),
            ],
            options={
                'db_table': 'governments',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank='Enter your choice', choices=[('coupons payment', 'coupons payment'), ('return sum governments', 'return sum governments')], max_length=30)),
                ('payment_date', models.DateField()),
                ('payment_sum', models.FloatField()),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_schedule', to='governments.governments')),
            ],
            options={
                'db_table': 'payments_schedule',
            },
        ),
        migrations.CreateModel(
            name='GovernmentIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayily_profit', models.FloatField()),
                ('month_profit', models.FloatField()),
                ('year_profit', models.FloatField()),
                ('total_profit', models.FloatField()),
                ('actual_rate', models.FloatField()),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governments_indicators', to='governments.governments')),
            ],
            options={
                'db_table': 'governments_indicators',
            },
        ),
    ]
