# Generated by Django 4.1.6 on 2023-05-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0002_rename_actual_rate_governmentindicators_bonds_current_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governments',
            name='bonds_repayment_nominal',
            field=models.FloatField(default=52),
            preserve_default=False,
        ),
    ]
