# Generated by Django 4.1.6 on 2023-05-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0004_remove_governmentindicators_bonds_current_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentindicators',
            name='government',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, related_name='governments_indicators', to='governments.governments'),
            preserve_default=False,
        ),
    ]
