# Generated by Django 4.1.6 on 2023-05-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0007_remove_governmentextendedindicators_coupons_current_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentextendedindicators',
            old_name='bonds_current_profit',
            new_name='coupons_profit',
        ),
    ]
