# Generated by Django 4.1.6 on 2023-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0008_rename_bonds_current_profit_governmentextendedindicators_coupons_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentextendedindicators',
            name='bonds_actual_profit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
