# Generated by Django 4.1.6 on 2023-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0009_governmentextendedindicators_bonds_actual_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentextendedindicators',
            name='bonds_difference_income',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governmentextendedindicators',
            name='bonds_income',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
