# Generated by Django 4.1.6 on 2023-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0012_remove_governmentextendedindicators_bonds_actual_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governments',
            name='type_gv',
            field=models.CharField(choices=[('SIM', 'SIM'), ('YTM', 'YTM')], max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('coupons payment', 'coupons payment'), ('return sum governments', 'return sum governments')], max_length=30),
        ),
    ]
