# Generated by Django 4.1.6 on 2023-05-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0013_alter_governments_type_gv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governments',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('PLN', 'PLN'), ('CHF', 'CHF'), ('GBP', 'GBP')], max_length=30),
        ),
    ]
