# Generated by Django 4.1.6 on 2023-05-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositindicators',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='loansindicators',
            name='loan',
        ),
        migrations.DeleteModel(
            name='deposit',
        ),
        migrations.DeleteModel(
            name='DepositIndicators',
        ),
        migrations.DeleteModel(
            name='loan',
        ),
        migrations.DeleteModel(
            name='LoansIndicators',
        ),
    ]
