# Generated by Django 4.1.6 on 2023-05-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sum', models.FloatField()),
                ('currency', models.CharField(blank='Enter your choice', choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('PLN', 'PLN'), ('CHF', 'CHF'), ('GBP', 'GBP')], max_length=30)),
                ('rate', models.FloatField()),
                ('period', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='LoansIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayily_profit', models.FloatField()),
                ('month_profit', models.FloatField()),
                ('year_profit', models.FloatField()),
                ('total_profit', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_indicators', to='loans.loans')),
            ],
            options={
                'db_table': 'loans_indicators',
            },
        ),
    ]
