# Generated by Django 4.1.6 on 2023-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
